name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Install Porter
        run: |
          curl -fsSLo porter "https://cdn.porter.sh/v1.0.0-rc.3/porter-linux-amd64"
          chmod +x porter

      - name: Test
        run: make test

      - name: GoReleaser Action
        if: ${{ !startsWith(github.ref, 'refs/tags/feed') }}
        uses: goreleaser/goreleaser-action@v2.0.2
        with:
          version: latest
          args: release --rm-dist --skip-validate --skip-sign
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PORTERPATH: ./porter
      - name: Delete Existing Feed
        uses: dev-drprasad/delete-tag-and-release@v0.1.2
        with:
          tag_name: feed
          delete_release: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare Feed
        id: prepare_feed
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: feed
          release_name: feed
          draft: false
          prerelease: false
      - name: Upload Feed
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.prepare_feed.outputs.upload_url }}
          asset_path: ./dist/atom.xml
          asset_name: atom.xml
          asset_content_type: application/xml
